### ISSUE TITLE
Original Traceback (most recent call last):   File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker     output = module(*input, **kwargs)   File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl     return forward_call(*input, **kwargs)   File "/home/EMS-YOLO/g1-resnet/models/yolo.py", line 131, in forward     input[i] = x RuntimeError: expand(torch.cuda.FloatTensor{[8, 5, 3, 320, 320]}, size=[8, 5, 3, 320]): the number of sizes provided (4) must be greater or equal to the number of dimensions in the tensor (5)

### ISSUE THREAD

**Issue by JonYuanHao** [BICLab/EMS-YOLO#11]
I have create gen1_data by replace train_g1 import dataset_g1T to import give_g1_data, and i have got train.txt and val.txt，but when i run: python train_g1.py，the pre-trained weights is best.pt, cfg file is models/resnet34.yaml.

**Comment by sumingming123** [comment]
Have you solved this problem? I also encountered the same problem.

**Comment by Qiaoyi-Su** [comment]
It seems the wrong corresponding file was used — the COCO dataset has one less dimension compared to GEN1.

**Comment by Qiaoyi-Su** [comment]
Has your issue been resolved? If not, contact me via email “[suqiaoyi2020@ia.ac.cn](mailto:suqiaoyi2020@ia.ac.cn)"— I can send you a separate version of the GEN1 code along with the preprocessed dataset.
