### ISSUE TITLE
give_g1_data.py def build_dataset的sample回傳是空的list...

### ISSUE THREAD

**Issue by 108360215** [BICLab/EMS-YOLO#14]

**Comment by 108360215** [comment]
個人推薦別用了 要改很多東西

**Comment by one00101** [comment]
请问您成功训练事件数据集GEN1了吗可以借鉴下是怎么修改的吗？目前报错是这样的，如何生成的这个txt文件呢？源码里面好像是空的
Traceback (most recent call last):
&nbsp; File "train_g1.py", line 639, in <module&gt;
&nbsp; &nbsp; main(opt)
&nbsp; File "train_g1.py", line 536, in main
&nbsp; &nbsp; train(opt.hyp, opt, device, callbacks)
&nbsp; File "train_g1.py", line 213, in train
&nbsp; &nbsp; train_loader, dataset = create_dataloader(train_path, opt.sample_size,opt.T,opt.image_shape, 'train', batch_size // WORLD_SIZE, gs, single_cls,
&nbsp; File "/root/EMS-YOLO-main/g1-resnet/utils/datasets_g1T.py", line 122, in create_dataloader
&nbsp; &nbsp; dataset = LoadImagesAndLabels(path, sample_size,T,image_shape, mode,batch=batch_size)
&nbsp; File "/root/EMS-YOLO-main/g1-resnet/utils/datasets_g1T.py", line 410, in __init__
&nbsp; &nbsp; with open(save_file_name) as t:
FileNotFoundError: [Errno 2] No such file or directory: '/root/autodl-tmp/GEN_part_5/train_a.txt'




赵锦秀
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BICLab/EMS-YOLO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月10日(星期三) 下午5:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BICLab/EMS-YOLO] give_g1_data.py def build_dataset的sample回傳是空的list... (Issue #14)





 
個人推薦別用了 要改很多東西

**Comment by CapricornGuang** [comment]
同问这个问题，首先我们是要下载那个200多个GB的GEN1数据集吗？

**Comment by 108360215** [comment]
That’s right

Yuguang Yang ***@***.***>於 2024年6月13日 週四，下午2:06寫道：

**Comment by CapricornGuang** [comment]
Thanks for your coming email

**Comment by Qiaoyi-Su** [comment]
这里还有一个当时处理好的数据集链接，https://cloud.tsinghua.edu.cn/f/4389040ffac446649736/
