### ISSUE TITLE
Missing 'DetectMultiBackend' class in models.common.py

### ISSUE THREAD

**Issue by CurryYH** [BICLab/EMS-YOLO#4]
ImportError: cannot import name 'DetectMultiBackend' from 'models.common'
I found the same DetectMultiBackend class in the YOLOv5 repository, which is used for multi-backend inference. But it appears to be incompatible with this version. Can you repush the common.py ?

**Comment by CurryYH** [comment]
你方便的话可以把代码发过来，我在本地debug一下看看

**Comment by CurryYH** [comment]
> 我也是加载了v5的DetectMultiBackend 类，但是每次运行时都需要重新下载数据集，请问您那边是这样的吗？
你方便的话可以把代码发过来，我在本地debug一下看看

**Comment by wangaiping1024** [comment]
> > 我也是加载了v5的DetectMultiBackend 类，但是每次运行时都需要重新下载数据集，请问您那边是这样的吗？
> > 你方便的话可以把代码发过来，我在本地debug一下看看



> > 我也是加载了v5的DetectMultiBackend 类，但是每次运行时都需要重新下载数据集，请问您那边是这样的吗？
> > 你方便的话可以把代码发过来，我在本地debug一下看看

我只是把v5的那个模块放进去了，但是我发现里面还是有点问题，比如yolo.py里面需要加载的这些if m in [Conv, GhostConv, Bottleneck, GhostBottleneck, SPP, SPPF, DWConv, MixConv2d, Focus, CrossConv,
                 BottleneckCSP, C3, C3TR, C3SPP, C3Ghost,Conv_2,snn_resnet,
                 BasicBlock,BasicBlock_1,BasicBlock_2,Conv_A,CSABlock,LIAFBlock,Conv_LIAF,Bottleneck_2,
                 TCSABlock,BasicTCSA,ConcatBlock_ms,BasicBlock_ms,Conv_1,Concat_res2,HAMBlock,ConcatCSA_res2,BasicBlock_ms1]好像有很多都没有，你那边调通了吗？

**Comment by CurryYH** [comment]
我这边也还在调试中

**Comment by wangaiping1024** [comment]
> 我这边也还在调试中

好的

**Comment by wangaiping1024** [comment]
您好，我也在调试，目前还没调通，如果调通了会发给您的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BICLab/EMS-YOLO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月10日(星期五) 晚上10:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BICLab/EMS-YOLO] Missing 'DetectMultiBackend' class in models.common.py (Issue #4)





  
我这边也还在调试中
  
如果您那边调通的话，请问可以分享一下吗？

**Comment by SJTU-DongHaoYan** [comment]
> 您好，我也在调试，目前还没调通，如果调通了会发给您的。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "BICLab/EMS-YOLO" ***@***.***&gt;; 发送时间:&nbsp;2023年11月10日(星期五) 晚上10:00 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [BICLab/EMS-YOLO] Missing 'DetectMultiBackend' class in models.common.py (Issue #4) 我这边也还在调试中 如果您那边调通的话，请问可以分享一下吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

好的，非常感谢！

**Comment by carrolltm** [comment]
The reason is that the author code uses yolov3, so i just try that  use detect.py to show the result, Functions that don't exist in EMS-yolo, my solution is to copy them from yolov3.
https://github.com/ultralytics/yolov3

**Comment by carrolltm** [comment]
![Uploading image.png…]()

**Comment by carrolltm** [comment]
To continue my speech above, I copied the yolov3 representative and showed the detection result, but I did not find the innovative module code in the author's paper!!!

**Comment by 54108** [comment]
> 原因是作者代码使用了 yolov3，所以我只是尝试使用 detect.py 来显示结果，EMS-yolo 中不存在的函数，我的解决方案是从 yolov3 复制它们。 https://github.com/ultralytics/yolov3

What files were copied?

**Comment by carrolltm** [comment]
> > 原因是作者代码使用了 yolov3，所以我只是尝试使用 detect.py 来显示结果，EMS-yolo 中不存在的函数，我的解决方案是从 yolov3 复制它们。 https://github.com/ultralytics/yolov3
> 
> What files were copied?

You can copy non-existent files while bebug debugging, i change some files:common.py,dtection.py, downloads.py, general.py,yolo.py.   i can show the result with the pretained model. but i don not to train. if you have other question, please give me your email

**Comment by liyisongRolling** [comment]
> > > 我也是加载了v5的DetectMultiBackend 类，但是每次运行时都需要重新下载数据集，请问您那边是这样的吗？
> > > 你方便的话可以把代码发过来，我在本地debug一下看看
> 
> > > 我也是加载了v5的DetectMultiBackend 类，但是每次运行时都需要重新下载数据集，请问您那边是这样的吗？
> > > 你方便的话可以把代码发过来，我在本地debug一下看看
> 
> 我只是把v5的那个模块放进去了，但是我发现里面还是有点问题，比如yolo.py里面需要加载的这些if m in [Conv, GhostConv, Bottleneck, GhostBottleneck, SPP, SPPF, DWConv, MixConv2d, Focus, CrossConv, BottleneckCSP, C3, C3TR, C3SPP, C3Ghost,Conv_2,snn_resnet, BasicBlock,BasicBlock_1,BasicBlock_2,Conv_A,CSABlock,LIAFBlock,Conv_LIAF,Bottleneck_2, TCSABlock,BasicTCSA,ConcatBlock_ms,BasicBlock_ms,Conv_1,Concat_res2,HAMBlock,ConcatCSA_res2,BasicBlock_ms1]好像有很多都没有，你那边调通了吗？

这些都是net的block，其实在很多结构中是没有用到的。例如他在论文中使用的两个结构，可以在models中的resnet18.yaml和resnet34.yaml中可以看到配置，骨干网络和检测头只用了Snn卷积层和BasicBlock_2。 所以对照网络配置，大胆将缺失的模块名删掉就行了。那些报错的模块你都可以在YOLOV3或者V5的源码中的model.common.py文件中找到。

**Comment by liyisongRolling** [comment]
> 我也是加载了v5的DetectMultiBackend 类，但是每次运行时都需要重新下载数据集，请问您那边是这样的吗？

[你可以在data.coco.yaml文件中，看到数据集的存放位置，或者修改path到你自己数据集的位置。而且COCO官方标签使用的是.json文件，你需要从YOLO作者GITHUB上下载他做好的.txt的文件，也就是coco2017Labels.zip 并解压到path下，和images同级

(url)https://github.com/ultralytics/yolov5/releases/download/v1.0/

**Comment by HouNic97** [comment]
> > > > 我也是加载了v5的DetectMultiBackend 类，但是每次运行时都需要重新下载数据集，请问您那边是这样的吗？
> > > > 你方便的话可以把代码发过来，我在本地debug一下看看
> > 
> > 
> > > > 我也是加载了v5的DetectMultiBackend 类，但是每次运行时都需要重新下载数据集，请问您那边是这样的吗？
> > > > 你方便的话可以把代码发过来，我在本地debug一下看看
> > 
> > 
> > 我只是把v5的那个模块放进去了，但是我发现里面还是有点问题，比如yolo.py里面需要加载的这些if m in [Conv, GhostConv, Bottleneck, GhostBottleneck, SPP, SPPF, DWConv, MixConv2d, Focus, CrossConv, BottleneckCSP, C3, C3TR, C3SPP, C3Ghost,Conv_2,snn_resnet, BasicBlock,BasicBlock_1,BasicBlock_2,Conv_A,CSABlock,LIAFBlock,Conv_LIAF,Bottleneck_2, TCSABlock,BasicTCSA,ConcatBlock_ms,BasicBlock_ms,Conv_1,Concat_res2,HAMBlock,ConcatCSA_res2,BasicBlock_ms1]好像有很多都没有，你那边调通了吗？
> 
> 这些都是net的block，其实在很多结构中是没有用到的。例如他在论文中使用的两个结构，可以在models中的resnet18.yaml和resnet34.yaml中可以看到配置，骨干网络和检测头只用了Snn卷积层和BasicBlock_2。 所以对照网络配置，大胆将缺失的模块名删掉就行了。那些报错的模块你都可以在YOLOV3或者V5的源码中的model.common.py文件中找到。

HEPL！i dont know what went wrong and how to solve this problem：


Traceback (most recent call last):
  File "detect.py", line 306, in <module>
    main(opt)
  File "detect.py", line 301, in main
    run(**vars(opt))
  File "D:\code\anaconda3\envs\coco\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 86, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn)
  File "D:\code\EMS-YOLO\EMS-YOLO\models\common.py", line 341, in __init__
    model = torch.jit.load(w) if 'torchscript' in w else attempt_load(weights, map_location=device)
  File "D:\code\EMS-YOLO\EMS-YOLO\models\experimental.py", line 93, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location=map_location)  # load
  File "D:\code\anaconda3\envs\coco\lib\site-packages\torch\serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "D:\code\anaconda3\envs\coco\lib\site-packages\torch\serialization.py", line 882, in _load
    result = unpickler.load()
  File "D:\code\anaconda3\envs\coco\lib\site-packages\torch\serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'Conv_1' on <module 'models.common' from 'D:\\code\\EMS-YOLO\\EMS-YOLO\\models\\common.py'>

**Comment by 54108** [comment]
> > > 原因是作者代码使用了 yolov3，所以我只是尝试使用 detect.py 来显示结果，EMS-yolo 中不存在的函数，我的解决方案是从 yolov3 复制它们。 https://github.com/ultralytics/yolov3
> > 
> > 
> > What files were copied?
> 
> You can copy non-existent files while bebug debugging, i change some files:common.py,dtection.py, downloads.py, general.py,yolo.py. i can show the result with the pretained model. but i don not to train. if you have other question, please give me your email

thanks，it work

**Comment by Qiaoyi-Su** [comment]
> > > > 我也是加载了v5的DetectMultiBackend 类，但是每次运行时都需要重新下载数据集，请问您那边是这样的吗？
> > > > 你方便的话可以把代码发过来，我在本地debug一下看看
> > 
> > 
> > > > 我也是加载了v5的DetectMultiBackend 类，但是每次运行时都需要重新下载数据集，请问您那边是这样的吗？
> > > > 你方便的话可以把代码发过来，我在本地debug一下看看
> > 
> > 
> > 我只是把v5的那个模块放进去了，但是我发现里面还是有点问题，比如yolo.py里面需要加载的这些if m in [Conv, GhostConv, Bottleneck, GhostBottleneck, SPP, SPPF, DWConv, MixConv2d, Focus, CrossConv, BottleneckCSP, C3, C3TR, C3SPP, C3Ghost,Conv_2,snn_resnet, BasicBlock,BasicBlock_1,BasicBlock_2,Conv_A,CSABlock,LIAFBlock,Conv_LIAF,Bottleneck_2, TCSABlock,BasicTCSA,ConcatBlock_ms,BasicBlock_ms,Conv_1,Concat_res2,HAMBlock,ConcatCSA_res2,BasicBlock_ms1]好像有很多都没有，你那边调通了吗？
> 
> 这些都是net的block，其实在很多结构中是没有用到的。例如他在论文中使用的两个结构，可以在models中的resnet18.yaml和resnet34.yaml中可以看到配置，骨干网络和检测头只用了Snn卷积层和BasicBlock_2。 所以对照网络配置，大胆将缺失的模块名删掉就行了。那些报错的模块你都可以在YOLOV3或者V5的源码中的model.common.py文件中找到。

**Comment by Fanty01** [comment]
有没有人成功复现代码？

**Comment by Nighfearti** [comment]
I can't import get_local from visualizer, how can I solve this?

**Comment by timefliesfang** [comment]
Why did the authors delete some code blocks on purpose??

**Comment by 108360215** [comment]
@carrolltm  Excuse me, could you tell me how to implement your detect.py on event data(.dat), and what is your cmd(python detect.py ...), Thanks you.

**Comment by HeuristicLU** [comment]
跑通了，分享给大家https://github.com/HeuristicLU/EMS-yolo

**Comment by sumingming123** [comment]
大家有遇到过这个问题吗？我已经同意了time_window设置参数，还是显示这个错误。Starting training for 250 epochs...

Epoch gpu_mem box obj cls labels img_size
0%| | 0/1 [00:00<?, ?it/s] /content/drive/MyDrive/EMS_YOLO_LU/g1_resnet/train_g1.py:343: FutureWarning: torch.cuda.amp.autocast(args...) 已弃用。请改用 torch.amp.autocast('cuda', args...)。
使用 amp.autocast(enabled=cuda):
0%| | 0/1 [00:00 <?，？it / s]
回溯（最近一次调用最后一次）：
文件“/content/drive/MyDrive/EMS_YOLO_LU/g1_resnet/train_g1.py”，第 662 行，在
main（opt）中
文件“/content/drive/MyDrive/EMS_YOLO_LU/g1_resnet/train_g1.py”，第 559 行，在主
训练（opt.hyp，opt，device，callbacks）
文件“/content/drive/MyDrive/EMS_YOLO_LU/g1_resnet/train_g1.py”，第 344 行，在训练中
pred = model（imgs）# 转发
文件“/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py”，第 1736 行，在 _wrapped_call_impl 中
返回 self._call_impl（*args，**kwargs）
文件“/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py”，第 1747 行，在 _call_impl 中
返回 forward_call(*args, **kwargs)
文件“/content/drive/MyDrive/EMS_YOLO_LU/models/yolo.py”，第 140 行，在 forward
输入[i] = x
RuntimeError: expand(torch.FloatTensor{[47, 5, 3, 320, 320]}, size=[47, 5, 3, 320]): 提供的尺寸数量 (4) 必须大于或等于张量中的维数 (5)
