### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [3, 32, 2, 2], expected input[1, 3, 256, 256] to have 32 channels, but got 3 channels instead

### ISSUE THREAD

**Issue by 108360215** [BICLab/EMS-YOLO#9]
My data is Gen1 data, I use command: "python train_g1.py", and I need help to solve this. could everyone help me. Thanks!

**Comment by HouNic97** [comment]
> My data is Gen1 data, I use command: "python train_g1.py", and I need help to solve this. could everyone help me. Thanks!

Hi bro，have you already solved Problem“Train_g1.py has no dataset about .txt” AND HOW？

**Comment by 108360215** [comment]
@HouNic97  I replace datasets_g1T.py with give_g1_data.py(LoadImagesAndLabels). But I still can't implement train_g1.py.

**Comment by HouNic97** [comment]
> @HouNic97 I replace datasets_g1T.py with give_g1_data.py(LoadImagesAndLabels). But I still can't implement train_g1.py.

<img width="759" alt="Q" src="https://github.com/BICLab/EMS-YOLO/assets/79568850/b7deebf8-035a-43dc-adee-a5a78b755823">

Thank you for your response. I don't quite understand the settings for these three paths. How did you set them, and where do I need to set them?（give_g1_data.py : line 410 ,line 440 and line 441）

**Comment by 108360215** [comment]
@HouNic97 Hi, I also try to figure out this source code. I am still not implementing on train_g1.py, if you work successfully pls tell me. Thanks.

**Comment by 108360215** [comment]
@HouNic97 I know these path should be your gen1 data file path

**Comment by ooYwY** [comment]
请问这个问题解决了吗 该怎么解决呢

**Comment by sumingming123** [comment]
Have you encountered this problem? I have agreed to the time_window setting parameters. This error is still displayed.Starting training for 250 epochs...

Epoch gpu_mem box obj cls labels img_size
0%| | 0/1 [00:00<?, ?it/s] /content/drive/MyDrive/EMS_YOLO_LU/g1_resnet/train_g1.py:343: FutureWarning: torch.cuda.amp.autocast(args...) is deprecated. Please use torch.amp.autocast('cuda', args...) instead.
with amp.autocast(enabled=cuda):
0%| | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
File "/content/drive/MyDrive/EMS_YOLO_LU/g1_resnet/train_g1.py", line 662, in
main(opt)
File "/content/drive/MyDrive/EMS_YOLO_LU/g1_resnet/train_g1.py", line 559, in main
train(opt.hyp, opt, device, callbacks)
File "/content/drive/MyDrive/EMS_YOLO_LU/g1_resnet/train_g1.py", line 344, in train
pred = model(imgs) # forward
File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
return forward_call(*args, **kwargs)
File "/content/drive/MyDrive/EMS_YOLO_LU/models/yolo.py", line 140, in forward
input[i] = x
RuntimeError: expand(torch.FloatTensor{[47, 5, 3, 320, 320]}, size=[47, 5, 3, 320]): the number of sizes provided (4) must be greater or equal to the number of dimensions in the tensor (5)

**Comment by Qiaoyi-Su** [comment]
> Have you encountered this problem? I have agreed to the time_window setting parameters. This error is still displayed.Starting training for 250 epochs...
> 
> Epoch gpu_mem box obj cls labels img_size 0%| | 0/1 [00:00<?, ?it/s] /content/drive/MyDrive/EMS_YOLO_LU/g1_resnet/train_g1.py:343: FutureWarning: torch.cuda.amp.autocast(args...) is deprecated. Please use torch.amp.autocast('cuda', args...) instead. with amp.autocast(enabled=cuda): 0%| | 0/1 [00:00<?, ?it/s] Traceback (most recent call last): File "/content/drive/MyDrive/EMS_YOLO_LU/g1_resnet/train_g1.py", line 662, in main(opt) File "/content/drive/MyDrive/EMS_YOLO_LU/g1_resnet/train_g1.py", line 559, in main train(opt.hyp, opt, device, callbacks) File "/content/drive/MyDrive/EMS_YOLO_LU/g1_resnet/train_g1.py", line 344, in train pred = model(imgs) # forward File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl return forward_call(*args, **kwargs) File "/content/drive/MyDrive/EMS_YOLO_LU/models/yolo.py", line 140, in forward input[i] = x RuntimeError: expand(torch.FloatTensor{[47, 5, 3, 320, 320]}, size=[47, 5, 3, 320]): the number of sizes provided (4) must be greater or equal to the number of dimensions in the tensor (5)

Has your issue been resolved? If not, feel free to contact me via email “suqiaoyi2020@ia.ac.cn"— I can send you a separate version of the GEN1 code along with the preprocessed dataset.
